version: '3.7'

services:
  influx:
    image: influxdb:1.6
    ports:
      - "8086:8086"
    volumes:
      - ./influx-data:/var/lib/influxdb
    networks:
      - influx

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - influx

networks:
  influx:
